# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('m2m-example', ['m2m', 'internet', 'netanim', 'mobility', 'olsr', 'core', 'stats', 'applications'])
    obj.source = 'm2m-example.cc'

